CREATE TABLE bookmarks_data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bookmark_title TEXT NOT NULL,
    bookmark_description TEXT,
    bookmark_rating INTEGER NOT NULL,
    bookmark_url TEXT NOT NULL
);